module.exports = {
  VERSION: 1,
  ASYNCHRONOUS_MSG: 'asynchronous-msg',
  ASYNCHRONOUS_MSG_REPLY: 'asynchronous-msg-reply',
  REPLY_PUSH: 'push',
  REPLY_CONNECT: 'connect',
  REPLY_DISCONNECT: 'disconnect',
  REPLY_PASTE: 'paste',
  REPLAY_PUSH_IMG: 'push_img',
  MODULE_SYS: 'sys',
  ACTION_INFO: 'info',
  MODULE_STEP: 'step',
  ACTION_APPEND: 'append',
  ACTION_REPLACE: 'replace',
  MODULE_DREAM_LIST: 'dream_list',
  MODULE_DREAM_DETAIL: 'dream_detail',
};
